<a href="https://colab.research.google.com/github/vainaijr/aiStartUp/blob/master/snippets_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# networkx

In [0]:
import networkx as nx
from networkx import nx

In [0]:
nx.grid_2d_graph
nx.lollipop_graph
nx.is_graphical

nx.configuration_model

for line in nx.generate_adjlist
for v in G.nodes():
nx.single_source_shortest_path_length

nx.radius
nx.diameter
nx.eccentricity
nx.center
nx.periphery
nx.density

nx.write_edgelist
nx.read_edgelist
nx.draw


# video

In [0]:
from IPython.display import HTML

# Youtube
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/S_f2qV2_U00?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>')

# eliot

In [0]:
!pip install eliot
!pip install eliot-tree

In [0]:
from eliot import log_call, to_file

to_file(open("out.log", "w"))

In [0]:
!eliot-tree out.log | grep -A1 double.*started

# function__

In [0]:
def add(a: int, b: int) -> int:
  """adds two numbers"""
  x = a + b
  return x

In [0]:
print(add.__doc__)

adds two numbers


In [0]:
print(add.__annotations__)

{'a': <class 'int'>, 'b': <class 'int'>, 'return': <class 'int'>}


In [0]:
print(add.__code__.co_varnames)

('a', 'b', 'x')


In [0]:
print(add.__closure__)

None


In [0]:
from inspect import signature
signature(add).parameters

mappingproxy({'a': <Parameter "a:int">, 'b': <Parameter "b:int">})

# call dunder

In [0]:
class Averager():
  def __init__(self):
    self.series = []
  
  def __call__(self, new_value):
    self.series.append(new_value)
    total = sum(self.series)
    return total / len(self.series)    

In [0]:
avg = Averager()

In [0]:
avg.__call__(10)

10.0

In [0]:
object.__call__?

In [0]:
def make_average():
  series = []
  
  def averager(new_value):
    series.append(new_value)
    total = sum(series)
    return total / len(series)
  
  return averager

In [0]:
avg = make_average()

In [0]:
avg(10)

10.0

# decorators in the standard library

In [0]:
@property
@classmethod
@staticmethod
@functools.wraps
@functools.singledispatch
@functools.total_ordering
@functools.lru_cache

# descriptors

In [0]:
# a descriptor encapsulates attribute getting / setting logic in a reusable way

In [0]:
# it is posible to use any class that implements __get__ or __set__ as a descriptor

# method resolution order

In [0]:
import inspect

In [0]:
inspect.getmro(type(3.14))

(float, object)

In [0]:
(1 == 1).__class__.__mro__

(bool, int, object)

# nvcc

In [0]:
!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git

In [0]:
%load_ext nvcc_plugin

In [0]:
%%cu

# os version 

In [0]:
%%bash
echo "$(</etc/os-release)"

# grep

In [0]:
!grep "WORLD" world/hi.txt

In [0]:
!grep -i "WORLD" world/hi.txt

hello world


In [0]:
!grep -iv "WORLD" world/hi.txt

In [0]:
!grep -v "WORLD" world/hi.txt

hello world


In [0]:
!grep -rn "he" *

world/hi.txt:1:hello world


# AdaptiveConcatPool2d

In [0]:
class AdaptiveConcatPool2d(nn.Module):
  def __init__(self, sz=1):
    super().__init__()
    self.output_size = sz
    self.ap = nn.AdaptiveAvgPool2d(sz)
    self.mp = nn.AdaptiveMaxPool2d(sz)
  
  def forward(self, x):
    return torch.cat([self.mp(x), self.ap(x)], 1)

In [0]:
nh = 40

m_new = nn.Sequential(m_cut, AdaptiveConcatPool2d(), Flatten(), nn.Linear(ni * 2, data.c_out))

# in-place

In [0]:
# example of not in-place

In [0]:
a = torch.randn(1)
b = torch.randn(1)

In [0]:
id(a)

140060066035968

In [0]:
id(b)

140060066034240

In [0]:
a = a + b # not in-place

In [0]:
id(a) # changed because not in-place

140060066034672

In [0]:
# example of in-place

In [0]:
c = torch.randn(1)
d = torch.randn(1)

In [0]:
id(c)

140060066037336

In [0]:
id(d)

140060066034888

In [0]:
c += d # +=, *= in-place

In [0]:
id(c) # no change because in-place

140060066037336

In [0]:
# another example of in-place

In [0]:
e = torch.randn(1)
f = torch.randn(1)

In [0]:
id(e)

140060066050624

In [0]:
id(f)

140060066050768

In [0]:
e.add_(f)

tensor([-1.9524])

In [0]:
id(e) # no change because in-place

140060066050624

In [0]:
# in PyTorch _ as postfix means in-place

In [0]:
e.add_(f) # in-place
e.sub_(f) # in-place

tensor([-1.9524])

In [0]:
id(e)

140060066050624

# fastai_listify

In [0]:
!pip install fastai
from fastai.train import listify
import torch

In [0]:
x = [1, 2, 3]
y = torch.arange(12)

In [0]:
x

[1, 2, 3]

In [0]:
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
z = listify((1), x)
z

[1, 1, 1]

In [0]:
a = listify(1, y)
a

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [0]:
b = listify((1, 2, 3), x)
b

[1, 2, 3]

In [0]:
c = listify('g', x)
c

['g', 'g', 'g']

# expand_as

In [0]:
a = torch.tensor([1, 2, 3])

In [0]:
b = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [0]:
c = a.expand_as(b)

In [0]:
c

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [0]:
d = a + b

In [0]:
d

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

# bs_val

In [0]:
bs*2

# fastai_callbacks

In [0]:
def train(learn, epochs, callback, metrics):
  cb_handler = CallbackHandler(callbacks)
  cb_handler.on_train_begin(epochs, learn, metrics)
  for epoch in range(epochs):
    learn.model.train()
    cb_handler.on_epoch_begin(epoch)
    for xb, yb in learn.data.train_dl:
      xb, yb = cb_handler.on_batch_begin(xb, yb)
      out = learn.model(xb)
      out = cb_handler.on_loss_begin(out)
      loss = learn.loss_func(out, yb)
      loss, skip_backward = callbacks.on_loss_begin(loss)
      if not skip_backward:
        loss.backward()
      if not cb_handler.on_step_begin():
        learn.opt.step()
      if not cb_handler.on_step_end():
        learn.opt.zero_grad()
      if not callbacks.on_batch_end():
        break
    val_loss, mets = validate(learn.data.valid_dl, model, metrics)
    if not callbacks.on_epoch_end(val_loss, mets):
      break
  callbacks.on_train_end()

In [0]:
class LRScheduler(LearnerCallback):
  def on_batch_begin(self, iteration, **kwargs):
    self.learn.opt.lr = my_function(iteration)

In [0]:
class EarlyStopping(Callback):
  def on_epoch_end(self, last_metrics, **kwargs):
    if not_happy(last_metrics):
      return {'stop_training': True}

In [0]:
class ParallelTrainer(LearnerCallback):
  _order = 20
  def on_train_begin(self, **kwargs):
    self.learn.model = DataParallel(self.learn.model)
  def on_train_end(self, **kwargs):
    self.learn.model = self.learn.model.module

In [0]:
class GradientClipping(LearnerCallback):
  def __init__(self, learn:Learner, clip:float = 0.):
    super().__init__(learn)
    self.clip = clip
  
  def on_backward_end(self, **kwargs):
    if self.clip:
      nn.utils.clip_grad_norm_(self.learn.model.parameters(), self.clip)